import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    position: 'absolute',
    top: 60,
    width: '100%',
    paddingHorizontal: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 100,
  },
  logo: { fontWeight: '900', fontSize: 14, letterSpacing: 3, color: 'white' },
  indicatorContainer: {
    flexDirection: 'row',
    width: 80,
    justifyContent: 'space-between',
  },
  indicatorTrack: {
    height: 3,
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.3)',
    marginHorizontal: 2,
    borderRadius: 2,
    overflow: 'hidden',
  },
  indicatorFill: { height: '100%', backgroundColor: 'white' },
  screen: { ...StyleSheet.absoluteFillObject },
  contentWrapper: { justifyContent: 'center', padding: 40 },
  highlightText: {
    fontWeight: '800',
    fontSize: 12,
    marginBottom: 12,
    letterSpacing: 2,
    color: 'rgba(255,255,255,0.6)',
  },
  title: {
    color: 'white',
    fontSize: 54,
    fontWeight: '900',
    lineHeight: 60,
    letterSpacing: -1.5,
  },
  subtitle: {
    color: 'white',
    fontSize: 18,
    marginTop: 18,
    lineHeight: 28,
    opacity: 0.8,
  },
  visualContainer: {
    height: 180,
    marginVertical: 40,
    justifyContent: 'center',
  },
  pipelineMain: {
    height: 60,
    width: '80%',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  dotPulse: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'white',
    marginRight: 15,
  },
  skeletonLine: { height: 6, borderRadius: 3, backgroundColor: 'white' },
  pipelineLink: {
    width: 2,
    height: 20,
    backgroundColor: 'white',
    opacity: 0.3,
    marginLeft: 40,
  },
  ringLarge: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ringMedium: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 8,
    borderColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  ringSmall: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'white',
  },
  timeLabel: {
    position: 'absolute',
    left: 140,
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  timeLabelText: {
    color: 'white',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  matrixGrid: { flexDirection: 'row', alignItems: 'center' },
  matrixBig: {
    width: 100,
    height: 100,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  matrixColumn: { marginLeft: 15 },
  matrixSmall: {
    width: 45,
    height: 45,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.15)',
    marginBottom: 10,
  },
  ctaButton: {
    backgroundColor: 'white',
    paddingVertical: 20,
    borderRadius: 24,
    alignItems: 'center',
    marginTop: 10,
  },
  ctaText: { fontWeight: '900', fontSize: 16 },
  handle: { position: 'absolute', zIndex: 200 },
  handleCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  handleArrow: { fontSize: 20, color: '#0F172A', fontWeight: 'bold' },
});
